require_relative 'config/environment'

desc "Prints hello world"
task :hello_world do
    puts "Hello World"
end

desc "Starts a console session"
task :console do 
    # sh "ruby db/seeds.rb"
    binding.pry
end