# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'sqlite3'
gem 'activerecord', '~> 5.2.3'
gem 'sinatra-activerecord'
gem 'pry'
gem 'require_all'
